### ISSUE TITLE
 Advanced Android in Kotlin: Notifications 1.1 [Step #4][TODO 1.5 is not found]

### ISSUE THREAD

**Issue by AliAkberAakash** [googlecodelabs/android-kotlin-notifications#12]
**Describe the problem**
At step 4 Notifications 1.1 TODO 1.5 is referenced, but its not present in the cloned project.

**In which lesson and step of the codelab can this issue be found?**
Lesson  1.1 + step 4

**codelab:** advanced-android-kotlin

**Comment by clalexni** [comment]
did you find it?

**Comment by clalexni** [comment]
nvm, I forgot to switch branch
